class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(630, 460)
		self.centralwidget = QtWidgets.QWidget(MainWindow)

		self.centralwidget.setObjectName("centralwidget")
		self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 75, 401, 181))
		self.gridLayoutWidget.setObjectName("gridLayoutWidget")
		self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.road_to_cms = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.road_to_cms.setObjectName("road_to_cms")
		self.gridLayout.addWidget(self.road_to_cms, 4, 1, 1, 1)
		self.road_to_site = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.road_to_site.setObjectName("road_to_site")
		self.gridLayout.addWidget(self.road_to_site, 2, 1, 1, 1)
		self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
		self.view_site = QtWidgets.QLineEdit(self.gridLayoutWidget)
		self.view_site.setObjectName("view_site")
		self.gridLayout.addWidget(self.view_site, 2, 0, 1, 1)
		self.view_cms = QtWidgets.QLineEdit(self.gridLayoutWidget)
		self.view_cms.setObjectName("view_cms")
		self.gridLayout.addWidget(self.view_cms, 4, 0, 1, 1)
		self.label = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
		self.OK = QtWidgets.QPushButton(self.centralwidget)
		self.OK.setGeometry(QtCore.QRect(195, 265, 93, 28))
		self.OK.setObjectName("OK")
		self.Cancel = QtWidgets.QPushButton(self.centralwidget)
		self.Cancel.setGeometry(QtCore.QRect(320, 265, 93, 28))
		self.Cancel.setObjectName("Cancel")
		self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 300, 301, 80))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
		self.radioButton.setObjectName("radioButton")
		self.horizontalLayout_4.addWidget(self.radioButton)
		self.Win = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
		self.Win.setObjectName("Win")
		self.horizontalLayout_4.addWidget(self.Win)
		self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
		self.radioButton_2.setObjectName("radioButton_2")
		self.horizontalLayout_4.addWidget(self.radioButton_2)
		self.comboBox = QtWidgets.QComboBox(self.centralwidget)
		self.comboBox.setGeometry(QtCore.QRect(500, 20, 90, 22))
		self.comboBox.setObjectName("comboBox")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.comboBox.addItem("")

		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 26))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		
	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "TransferCMS"))
		self.road_to_cms.setText(_translate("MainWindow", "Выбрать"))
		self.road_to_site.setText(_translate("MainWindow", "Выбрать"))
		self.label_2.setText(_translate("MainWindow", "Укажите путь к папке с ядром CMS"))
		self.label.setText(_translate("MainWindow", "Укажите путь к папке с сайтом"))
		self.OK.setText(_translate("MainWindow", "OK"))
		self.Cancel.setText(_translate("MainWindow", "Отмена"))
		self.radioButton.setText(_translate("MainWindow", "Linux"))
		self.Win.setText(_translate("MainWindow", "Windows"))
		self.radioButton_2.setText(_translate("MainWindow", "MacOS"))
		self.comboBox.setItemText(0, _translate("MainWindow", "UTF-8"))
		self.comboBox.setItemText(1, _translate("MainWindow", "Win1251"))
		self.comboBox.setItemText(2, _translate("MainWindow", "DOS 866"))
